- hosts: localhost
  become: true
  tasks:
    - name: General dependencies
      become: true
      package:
        name:
          - openssl-devel
          - readline-devel
          - zlib-devel
          - libcurl-devel
          - uuid-devel
          - libuuid-devel
          - autoconf
          - automake
          - ncurses-devel
          - gcc-c++
        state: present
