- hosts: localhost
  become: true
  tasks:
    - name: General dependencies
      become: true
      package:
        name:
          - openssl-devel
          - readline-devel
          - zlib-devel
          - libcurl-devel
          - uuid-devel
          - libuuid-devel
          - autoconf
          - automake
          - ncurses-devel
          - gcc-c++
        state: present

    - name: Nice tools
      become: true
      package:
        name:
          - neofetch
          - picom
        state: present

    - name: Neovim installation
      become: true
      package:
        name:
          - neovim
          - python3-neovim
          - ripgrep
          - fd-find
        state: present
    - name: Neovim configuration
      become: false
      git:
        repo: git@github.com:worming004/nvim-ide.git
        dest: ~/.config/nvim

    - name: Tmux installation
      become: true
      package:
        name:
          - tmux
        state: present
    - name: Tmux configuration
      become: false
      git:
        repo: git@github.com:worming004/tmux-conf.git
        dest: ~/.config/tmux

    - name: I3 installation
      become: true
      package:
        name:
          - i3
          - i3status
          - dmenu
          - i3lock
          - xbacklight
          - feh
          - conky
    - name: I3 configuration
      become: false
      git:
        repo: git@github.com:worming004/i3-config.git
        dest: ~/.config/i3

    - name: Kitty installation
      become: true
      package:
        name: 
          - kitty
        state: present
    - name: Kitty configuration
      become: false
      lineinfile:
        path: ~/.profile 
        line: "export TERMINAL=/usr/bin/kitty"

    - name: Dotnet installation
      become: true
      package:
        name:
          - dotnet-sdk-7.0
        state: present

    - name: Asdf installation
      become: false
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: v0.11.3
    - name: Asdf configuration
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: '{{ item }}'
      with_items:
        - '. "$HOME/.asdf/asdf.sh"'
        - '. "$HOME/.asdf/completions/asdf.bash"'

    - name: Aliases
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: '{{ item }}'
      with_items:
        - "alias nv='nvim'"
        - "alias gpa='git pull --all'"
        - "alias gp='git push'"
        - "alias ga='git add .'"
        - "alias lz='lazygit'"
        - "alias k='kubectl'"
        - "alias min='minikube'"
        - "alias tm='tmux'"
        - "alias pm='podman'"
        - "alias kit-cat='kitten +kitten icat'"

    - name: Other Utilities
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: '{{ item }}'
      with_items:
        - "source <(kubectl completion zsh)"
        - "source <(minikube completion zsh)"
    
    - name: Zsh config
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: '{{ item }}'
      with_items:
        - 'export ZSH="$HOME/.oh-my-zsh"'
        - 'ZSH_THEME="essembeh"'
        - "plugins=(git)"
        - "source $ZSH/oh-my-zsh.sh"
        - "SHELL=$(which zsh)"
        - "autoload -U +X compinit && compinit"
        - "autoload -U +X bashcompinit && bashcompinit"
        - "export HISTSIZE=1000000000"
        - "export SAVEHIST=$HISTSIZE"
        - "setopt EXTENDED_HISTORY"
        - "[ -z \"$TMUX\" ] && neofetch"

    - name: postgres
      become: true
      package:
        name:
          - postgresql
          - postgresql-contrib
        state: present
