- hosts: localhost
  become: true
  name: Tools
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Check if Neovim is installed and get version
      command: nvim --version
      register: neovim_version
      ignore_errors: yes

    - name: Set fact if Neovim is installed and at the desired version
      set_fact:
        neovim_installed: "{{ neovim_version.stdout is defined and 'NVIM v0.11.4' in neovim_version.stdout and '-dev-' not in neovim_version.stdout }}"
    # print value of neovim_installed
    #
    - debug: var=neovim_installed

    - name: Neovim common dependencies install
      become: true
      ansible.builtin.package:
        name:
        - ripgrep
        - cmake
        - gettext
        state: present

    - name: Debug Neovim version
      debug:
        msg: "Neovim is installed and at the expected version. Skipping"
      when: neovim_installed

    - name: Neovim uninstall neovim installed with package manager
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      when: not neovim_installed
      ansible.builtin.package:
        name:
          - neovim
          - neovim-nightly-bin-debug
        state: absent

    - name: Neovim dependencies install for MacOSX
      when: ansible_distribution == "MacOSX" and not neovim_installed
      become: true
      ansible.builtin.package:
        name:
        - ninja
        - cmake
        - gettext
        - curl
        state: present
        
    - name: neovim clone 
      become: false
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: ~/git/neovim/neovim
        version: v0.11.4
        force: true
      when: not neovim_installed

    - name: remove neovim build directory
      become: false
      ansible.builtin.file:
        path:  ~/git/neovim/neovim/build
        state: absent

    - name: remove neovim deps directory
      become: false
      ansible.builtin.file:
        path:  ~/git/neovim/neovim/.deps
        state: absent

    - name: neovim build
      become: false
      ansible.builtin.command:
        chdir: "{{ user_home }}/git/neovim/neovim"
        cmd: |
          make CMAKE_BUILD_TYPE=Release
      when: not neovim_installed
      
    - name: neovim install
      become: true
      ansible.builtin.command:
        chdir: "{{ user_home }}/git/neovim/neovim"
        cmd: |
          make install
      when: not neovim_installed

    - name: Check if Neovim is installed and get version
      command: nvim --version
      register: neovim_version_post_install
    
    - name: print output
      debug:
        msg: "{{ neovim_version_post_install.stdout }}"
