- hosts: localhost
  become: true
  name: Tools
  tasks:
    - name: Sway dependencies for wsl Ubuntu
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: true
      ansible.builtin.package:
        name:
        - wofi
        - kitty
        - mesa-utils
        - libglu1-mesa-dev 
        - freeglut3
        - mesa-common-dev
        - waybar
        - xwayland
        state: present
