- hosts: localhost
  become: true
  name: Tools
  tasks:
    - name: General dependencies Fedora (legacy)
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      when: ansible_distribution == "Fedora"
      ansible.builtin.package:
        name:
          - openssl-devel
          - readline-devel
          - zlib-devel
          - libcurl-devel
          - uuid-devel
          - libuuid-devel
          - autoconf
          - automake
          - ncurses-devel
          - gcc-c++
          - libyaml-devel
          - zig
          - picom
          - postgresql
          - postgresql-contrib
        state: present

    # - name: Ubuntu add redis repository
    #   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    #   block:
    #     - name: Add redis gpg
    #       ansible.builtin.get_url:
    #         url: https://packages.redis.io/gpg
    #         dest: /usr/share/keyrings/redis-archive-keyring.gpg
    #
    #     - name: Add redis source
    #       ansible.builtin.apt_repository:
    #         repo: "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb jammy stable"
    #         state: present

    - name: General dependencies Ubuntu
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: true
      ansible.builtin.package:
        name:
        - autoconf
        - automake
        - build-essential
        - libssl-dev
        - libncurses5-dev
        - unzip
        - python3-pip
        - inotify-tools
        - postgresql
        - postgresql-contrib
        - gpg
        - curl
        - redis-server
        - maim
        - fd-find
        state: present

    - name: General dependencies Arch
      when: ansible_distribution == "Archlinux"
      ansible.builtin.package:
        name:
        - autoconf
        - automake
        - unzip
        - inotify-tools
        - zig
        - fd
        - picom
        - ripgrep
        - postgresql
        - maim
        - dotnet-runtime
        - dotnet-sdk
        - waybar
        state: present

    - name: Obsolete dependencies Arch
      when: ansible_distribution == "Archlinux"
      ansible.builtin.package:
        name:
          - pinta
        state: absent

    - name: Nice tools
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ansible.builtin.package:
        name:
          - neofetch
          - thefuck
          - ranger
          - zsh
          - bat
          - podman
          - most
        state: present
    
    - name: Neovim installation
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      when: ansible_distribution != "Archlinux"
      ansible.builtin.package:
        name:
          - neovim
          - ripgrep
        state: present

    - name: Tmux installation
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ansible.builtin.package:
        name:
          - tmux
        state: present

        # TODO: install dotnet for macos
    - name: Dotnet installation
      become: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
      ansible.builtin.package:
        name:
          - dotnet-sdk-8.0
          - dotnet-runtime-8.0
          - dotnet-sdk-6.0
          - dotnet-runtime-6.0
        state: present

    # Wait a little bit before removing dotnet 7
    # - name: Dotnet Cleanup
    #   become: 
    #   when: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
    #   ansible.builtin.package:
    #     name:
    #       - dotnet-sdk-7.0
    #     state: absent

    - name: Asdf installation
      become: false
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: v0.11.3

    - name: Zsh auto suggestion
      become: false
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Zsh syntax-highlighting
      become: false
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Zsh terraform
      become: false
      ansible.builtin.git:
        repo: https://github.com/macunha1/zsh-terraform
        dest: ~/.oh-my-zsh/custom}/plugins/terraform

    - name: Zsh common config file
      become: false
      ansible.builtin.copy:
        src: ./.zshrc.common
        dest: ~/.zshrc.common
        mode: '0644'

    - name: Alias file
      become: false
      ansible.builtin.copy:
        src: ./.alias
        dest: ~/.alias
        mode: '0644'

    - name: Source common zsh config
      become: false
      ansible.builtin.lineinfile:
        dest: ~/.zshrc
        line: 'source ~/.zshrc.common'

    - name: Neovim configuration
      become: false
      ansible.builtin.git:
        repo: git@github.com:worming004/nvim-ide.git
        dest: ~/.config/nvim

    - name: Tmux plugins
      become: false
      ansible.builtin.git:
        repo: git@github.com:tmux-plugins/tpm
        dest: ~/.config/tmux-plugins/tpm

    - name: Tmux configuration
      become: false
      ansible.builtin.git:
        repo: git@github.com:worming004/tmux-conf.git
        dest: ~/.config/tmux

    - name: Kitty configuration
      become: false
      ansible.builtin.git:
        repo: git@github.com:worming004/kitty.git
        dest: ~/.config/kitty

    - name: Waybar configuration
      become: false
      ansible.builtin.git:
        repo: git@github.com:worming004/waybar.git
        dest: ~/.config/waybar
