- hosts: localhost
  become: true
  tasks:
    - name: General dependencies Mac
      when: ansible_distribution == 'MacOSX'
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ignore_errors: true
      package:
        name:
          - openssl-devel
          - readline-devel
          - zlib-devel
          - libcurl-devel
          - uuid-devel
          - libuuid-devel
          - autoconf
          - automake
          - ncurses-devel
          - gcc-c++
          - libyaml-devel
          - zig
          - dotnet-sdk-6
        state: present

    - name: General dependencies Ubuntu
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: true
      ignore_errors: true
      package:
        name:
          - autoconf
          - automake
          - build-essential
          - libssl-dev
          - libncurses5-dev
          - unzip
          - dotnet-sdk-6
          - pip3
        state: present

    - name: Nice tools
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ignore_errors: true
      package:
        name:
          - neofetch
          - thefuck
          - picom
          - pinta
          - ranger
          - zsh
          - bat
          - podman
        state: present

    - name: Neovim installation
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ignore_errors: true
      package:
        name:
          - neovim
          - python3-neovim
          - ripgrep
          - fd-find
        state: present


    - name: Tmux installation
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ignore_errors: true
      package:
        name:
          - tmux
        state: present

    - name: Dotnet installation
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ignore_errors: true
      package:
        name:
          - dotnet-sdk-7.0
        state: present

    - name: Asdf installation
      become: false
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: v0.11.3

    - name: Zsh auto suggestion
      become: false
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Zsh syntax-highlighting
      become: false
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Zsh common config file
      become: false
      copy:
        src: ./.zshrc.common
        dest: ~/.zshrc.common
        mode: '0644'

    - name: Source common zsh config
      become: false
      lineinfile:
        dest: ~/.zshrc
        line: 'source ~/.zshrc.common'

    - name: Neovim configuration
      become: false
      git:
        repo: git@github.com:worming004/nvim-ide.git
        dest: ~/.config/nvim

    - name: Tmux configuration
      become: false
      git:
        repo: git@github.com:worming004/tmux-conf.git
        dest: ~/.config/tmux

    - name: postgres
      become: "{{ ansible_facts['distribution'] != 'MacOSX' }}"
      ignore_errors: true
      package:
        name:
          - postgresql
          - postgresql-contrib
        state: present

